version: "3.8"
services:
  dictionary:
    image: brendanburns/dictionary-server
    restart: unless-stopped
    ports:
#      - 9090:8080
      - ${DICTIONARY_PORT}:8080
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
#    environment:
#      MYSQL_USER: librarian
#      MYSQL_PASSWORD: secret
#      MYSQL_DATABASE: dictionary
#      MYSQL_ROOT_PASSWORD: secret
    ports:
#      - 3306:3306
      - ${MYSQL_PORT}:3306
    depends_on:
      - dictionary
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      PMA_USER: librarian
#      PMA_PASSWORD: secret
    ports:
#      - 8080:80
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
  backend:
    build:
      context: ./backend
    env_file:
      - .env
#    environment:
#      NODE_ENV: ${NODE_ENV}
#      NPM_CONFIG_LOGLEVEL: ${NPM_CONFIG_LOGLEVEL}
    restart: unless-stopped
    ports:
#      - 3000:3000
      - ${BACKEND_PORT}:3000
    volumes:
      - ./backend:/app
      - ./scripts:/scripts
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
#    environment:
#      NODE_ENV: ${NODE_ENV}
#      NPM_CONFIG_LOGLEVEL: ${NPM_CONFIG_LOGLEVEL}
    restart: unless-stopped
    ports:
#      - 80:3000
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/app
      - ./scripts:/scripts
    depends_on:
      - backend
