version: "3.8"
services:
  dictionary:
    image: brendanburns/dictionary-server
    restart: unless-stopped
    ports:
      - ${DICTIONARY_PORT}:8080
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:3306
    depends_on:
      - dictionary
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./backend:/app
      - ./scripts:/scripts
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/app
      - ./scripts:/scripts
    depends_on:
      - backend
